language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - nightly
    - pypy
    - pypy3
script:
  - python setup.py flake8
  - python setup.py test
  - rstcheck README.rst CHANGES.rst
cache: pip
