language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
#   - nightly (https://github.com/eliben/pycparser/issues/251)
    - pypy
    - pypy3
script:
  - python setup.py flake8
  - python setup.py test
  - python setup.py check -m -r -s
cache: pip
